import dumIcon from "../../assets/images/Dashboard/Profil.png";

const DUMMY_EVENTS = [
  {
    name: "Music Event",
    location: "A Block/Nermin Tarhan",
    clubName: "Music Club",
    clubLogo: dumIcon,
    startTime: "13:20",
    endTime: "14:20",
    day: 7,
    month: 4,
  },
  {
    name: "Musica Event",
    location: "A Block/Nermin Tarhan",
    clubName: "Music Club",
    clubLogo: dumIcon,
    startTime: "13:20",
    endTime: "14:20",
    day: 20,
    month: 4,
  },
  {
    name: "Music Event",
    location: "A Block/Nermin Tarhan",
    clubName: "Music Club",
    clubLogo: dumIcon,
    startTime: "13:20",
    endTime: "14:20",
    day: 11,
    month: 4,
  },
  {
    name: "Music Event",
    location: "A Block/Nermin Tarhan",
    clubName: "Music Club",
    clubLogo: dumIcon,
    startTime: "13:20",
    endTime: "14:20",
    day: 20,
    month: 4,
  },
  {
    name: "Music Event 2",
    location: "A Block/Nermin Tarhan",
    clubName: "Music Club",
    clubLogo: dumIcon,
    startTime: "13:20",
    endTime: "14:20",
    day: 7,
    month: 4,
  },
  {
    name: "Music Event",
    location: "A Block/Nermin Tarhan",
    clubName: "Music Club",
    clubLogo: dumIcon,
    startTime: "13:20",
    endTime: "14:20",
    day: 20,
    month: 4,
  },
  {
    name: "Music Event",
    location: "A Block/Nermin Tarhan",
    clubName: "Music Club",
    clubLogo: dumIcon,
    startTime: "13:20",
    endTime: "14:20",
    day: 27,
    month: 4,
  },
];

export default DUMMY_EVENTS;
